services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=orbit'
      - 'MYSQL_USER=orbit_user'
      - 'MYSQL_PASSWORD=orbit_dev_pw'
      - 'MYSQL_ROOT_PASSWORD=orbit_root_pw'
    ports:
      - '3307:3306'