spring:
  application:
    name: orbit

  datasource:
    url: jdbc:mysql://localhost:3307/orbit
    username: orbit_user
    password: orbit_dev_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true